### ISSUE TITLE
Plugin installation instructions may be out of date for v2.x

### ISSUE THREAD

**Issue by frosencrantz** [jsvine/intro-to-visidata#20]
These instructions appear to be out-of-date for 2.x:
 - https://jsvine.github.io/intro-to-visidata/advanced/extending-visidata/

The doc for the new version is here: 
 - https://github.com/saulpw/visidata/blob/develop/docs/plugins.md

**Comment by anjakefala** [comment]
The plugin docs written by jsvine would still work for 2.x!

Since 1.5.2, a system for the automatic installation of plugins has been undergoing development. That affected the user guide for the structure of the `~/.visidata` directory. I wanted the automatic installation and manual installation to not conflict with one another.

(Also, it is wise to not update "intro-to-visidata" with plugin instructions yet, because this is all very much still under active conversation and development. https://github.com/saulpw/visidata/issues/448 is one example).

**Comment by frosencrantz** [comment]
@anjakefala is the plan to fix Visidata plugin installation before the release of 2.x?  Or will that be an ongoing conversation/development after release?

The intro-to-visidata instructions place the plugin code directly in the `.visidata` directory, while you've been documenting the `.visidata/plugins` directory.   Not sure if that matters.  I suspect the plugins directory could be used for earlier versions of visidata, too.  Also, not sure if that would conflict with upgrading.

**Comment by anjakefala** [comment]
```
is the plan to fix Visidata plugin installation before the release of 2.x? Or will that be an ongoing conversation/development after release?
```

This is part of the 2.x work.

**Comment by frosencrantz** [comment]
@anjakefala Would it make sense to update the Intro to suggest using `.visidata/plugins` directory instead of the `.visidata` directory?  I think that would still work for the stable version.

**Comment by anjakefala** [comment]
I would not complicate the default docs, yet! But yes, it would work for the `stable` version. =)

**Comment by jsvine** [comment]
Tutorial now updated for v2.0! (Or at least provisionally!) I have not changed the directory suggestion for installing custom plugins, but have added the plugin installer.
