### ISSUE TITLE
Useful to mention the keyboard layout philosophy.

### ISSUE THREAD

**Issue by frosencrantz** [jsvine/intro-to-visidata#23]
There are several general guidelines used for the keyboard short cuts in Visidata, which I learned later, but seem useful for this tutorial somewhere:

  * `g` vs `z` prefixes are typically used for wider vs narrower version of the same command
     * But there are exceptions, there is also an effort to have the non-prefixed version be for the most common case, which might overide the above.
  * number row symbols are used for column type modifications
  * Matching keys (e.g. parentheses) typically do the same but opposite (e.g sort descending vs ascending)

There may be more, but those are three I know.  Also, for the long commands there are some common nouns and verbs.

**Comment by jsvine** [comment]
Thanks for the notes! Responses below:

> g vs z prefixes are typically used for wider vs narrower version of the same command 

Yep, that's discussed [here](https://jsvine.github.io/intro-to-visidata/basics/navigating-visidata/#how-to-move-faster) and [here](https://jsvine.github.io/intro-to-visidata/basics/understanding-columns/#how-to-expand-shrink-and-remove-columns). Rather than add a preface about the philosophy, I've aimed to introduce the concepts as they arise while the reader is going through the tutorial.

> number row symbols are used for column type modifications

Column-typing commands are reviewed [here](https://jsvine.github.io/intro-to-visidata/basics/understanding-columns/#how-to-set-column-types). It doesn't mention the fact that they're in the number row (in part because not all keyboard layouts are the same), but I might consider adding a parenthetical of some sort along those lines.

> Matching keys (e.g. parentheses) typically do the same but opposite (e.g sort descending vs ascending)

That may be interesting to note. On the other hand, I think this may be self-evident to readers and I may leave out for concision's sake. But I'll think about it a bit more.

**Comment by frosencrantz** [comment]
I guess I did learn about `g` and `z` here.  :)  

Up to you how  any of this can be incorporated.  For sorting there was a logic to me about the opposite, but for some of the other keys I missed that right away.  Maybe because there are so many keys, it wasn't clear to me there was some logic to it all.

Anyways, I do think your tutorial does a fantastic job of helping people understand how to use VisiData.  Thanks again!

**Comment by jsvine** [comment]
Thanks for the kind words, @frosencrantz!

I can totally see the argument for some sort of philosophical overview. Maybe it's a sort of coda or appendix to the tutorial. Or maybe it's something best expressed in the official documentation, and linked from here to there. Regardless, I appreciate you raising the question.
